# POST http://localhost:5001/api/simulation/start
POST https://simulatorbackend.onrender.com/api/simulation/start
Content-Type: application/json

{
  "caseId": "VP-ABD-002"
}

###

# POST http://localhost:5001/api/simulation/ask
GET https://simulatorbackend.onrender.com/api/simulation/ask
Content-Type: application/json

{
  "sessionId": "b1c8a619-ed8c-44d4-a80b-0325d3b88853",
  "question": "HOW ARE YOUR FEELING TODAY?"
}