POST http://localhost:5001/api/simulation/start
#POST https://simulatorbackend.onrender.com/api/simulation/start
Content-Type: application/json

{
  "caseId": "VP-ABD-002"
}

###

POST http://localhost:5001/api/simulation/ask
#POST https://simulatorbackend.onrender.com/api/simulation/ask
Content-Type: application/json

{
  "sessionId": "2f2126bd-abf1-42aa-bb33-3e193677e74a",
  "question": "HOW ARE YOUR FEELING TODAY?"
}

###

 GET http://localhost:5001/api/simulation/cases
# GET https://simulatorbackend.onrender.com/api/simulation/cases
Content-Type: application/json

